services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgresCrudApi
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: